<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-12 at 21:15:54.
 */

require_once 'narcisista.php';

class narcisistaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var narcisista
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new narcisista;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers narcisista::__constructor
     * @todo   Implement test__constructor().
     */
    public function test__constructor() {
    }

    /**
     * @covers narcisista::es_narcisista
     * @todo   Implement testEs_narcisista().
     */
    public function testEs_narcisista() {
        // Remove the following lines when you implement this test.
       $this->assertEquals( true , $this->object->es_narcisista(1));
       $this->assertEquals( true , $this->object->es_narcisista(153));
       $this->assertEquals( true , $this->object->es_narcisista(8208));
    }

}
