<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-12 at 20:48:17.
 */
require_once 'multiplica.php';

class multiplicaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var multiplica
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new multiplica();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers multiplica::__constructor
     * @todo   Implement test__constructor().
     */
    public function test__constructor() {
        // Remove the following lines when you implement this test.
        
    }

    public function test2x1() {
        $this->assertEquals( 2, $this->object->multiplica(2, 1));
    }

}
