<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-11-12 at 21:34:43.
 */
require_once 'triangulo.php';

class trianguloTest extends PHPUnit_Framework_TestCase {

    /**
     * @var triangulo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new triangulo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers triangulo::__constructor
     * @todo   Implement test__constructor().
     */
    public function test__constructor() {
        
    }

    /**
     * @covers triangulo::tercerangulo
     * @todo   Implement testTercerangulo().
     */
    public function testTercerangulo_150() {
        $this->assertEquals(150, $this->object->tercerangulo(10, 20));
    }

    public function testTercerangulo_110() {
        $this->assertEquals(110, $this->object->tercerangulo(50, 20));
    }

    public function testTercerangulo_95() {
        $this->assertEquals(95, $this->object->tercerangulo(75, 10));
    }

}
